languange: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t arvind412/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arvind412/react-test npm test -- --coverage

after_success:
  - docker build -t arvind412/multi-client ./client
  - docker build -t arvind412/multi-nginx ./nginx
  - docker build -t arvind412/multi-server ./server
  - docker build -t arvind412/multi-worker ./worker

  # Take all images and push to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push arvind412/multi-client
  - docker push arvind412/multi-nginx
  - docker push arvind412/multi-server
  - docker push arvind412/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-251043900428
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

